// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ObiwanApikey struct {
	ID        uuid.UUID
	Projectid uuid.UUID
	Key       string
	Createdat time.Time
	Updatedat time.Time
	Deletedat sql.NullTime
}

type ObiwanOrganisation struct {
	ID                  uuid.UUID
	Name                string
	Description         sql.NullString
	Address             sql.NullString
	City                sql.NullString
	State               sql.NullString
	Zip                 sql.NullString
	Phone               sql.NullString
	Website             sql.NullString
	Email               string
	Status              interface{}
	Preferredbotservice sql.NullString
	Createdat           time.Time
	Updatedat           time.Time
	Deletedat           sql.NullTime
}

type ObiwanOrganisationprofile struct {
	ID               uuid.UUID
	Organisationid   uuid.UUID
	Initialquestions json.RawMessage
	Createdat        time.Time
	Updatedat        time.Time
	Deletedat        sql.NullTime
}

type ObiwanProject struct {
	ID             uuid.UUID
	Organisationid uuid.UUID
	Name           string
	Description    sql.NullString
	Createdat      time.Time
	Updatedat      time.Time
	Deletedat      sql.NullTime
}

type ObiwanProjectsorganisation struct {
	ID             uuid.UUID
	Projectid      uuid.UUID
	Organisationid uuid.UUID
	Createdat      time.Time
	Updatedat      time.Time
	Deletedat      sql.NullTime
}

type ObiwanUser struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Firstname string
	Lastname  string
	Dob       time.Time
	Createdat time.Time
	Updatedat time.Time
	Deletedat sql.NullTime
}

type ObiwanUsersorganisation struct {
	ID             uuid.UUID
	Organisationid uuid.UUID
	Userid         uuid.UUID
	Createdat      time.Time
	Updatedat      time.Time
	Deletedat      sql.NullTime
}
